meshLogging: info
sources:
    - name: GraphQLApi
      handler:
          graphql:
              endpoint: http://localhost:8080/graphql
              multipart: true
              operationHeaders:
                  Api-Authorization: "{context.headers['authorization']}"
    - name: AuthAccessGraphQLApi
      handler:
          graphql:
              endpoint: http://localhost:8088/graphql
              multipart: true
              operationHeaders:
                  Api-Authorization: "{context.headers['authorization']}"

    # - name: MySQLApi
    #   handler:
    #       mysql:
    #           host: localhost
    #           port: 3306
    #           user: root
    #           password: '123456'
    #           database: test

serve:
    exampleQuery: |
        query companies ($where: CompanyWhereInput, $orderBy: [QueryCompaniesOrderByOrderByClause!], $trashed: Trashed) {
          companies (where: $where, orderBy: $orderBy, trashed: $trashed) {
                id
                name
                status
                order
                organizations {
                    id
                    name
                    status
                }
            }
        }
