# adx_manage
# ~/Works/Git/aben/Projects/graphql-gateway
# yarn run dev

meshLogging: info
sources:
    # kol_id_core
    # ~/Works/Git/Maplehaze/kol_id_core
    # php -S 0.0.0.0:8080 -t public
    - name: GraphQLApi
      handler:
          graphql:
              endpoint: http://localhost:8080/graphql
              multipart: true
              operationHeaders:
                  Api-Authorization: "{context.headers['authorization']}"
    # adx_manage
    # ~/Works/Git/Maplehaze/adx_manage
    # php -S 0.0.0.0:8088 -t public
    - name: AuthAccessGraphQLApi
      handler:
          graphql:
              endpoint: http://localhost:8088/graphql
              multipart: true
              operationHeaders:
                  Authorization: "{context.headers['authorization']}"
    # dau
    # ~/Works/Git/Maplehaze/ssp_statistics_core/src
    # air
    # - name: DAURESTFulApi
    #   handler:
    #       jsonSchema:
    #           baseUrl: http://localhost:8081/dau
    #           operations:
    #               - type: Query
    #                 field: hourlyResults
    #                 path: /hourlyresults?app_id={args.appId}&from={args.from}&to={args.to}
    #                 argTypeMap:
    #                     appId: String!
    #                     from: String
    #                     to: String
    #                 method: GET
    #                 responseSchema: ./json-schemas/hourlyresult.json#/definitions/HourlyResults
serve:
    port: 4000
    cors:
        origin: '*' # just for test.
    playground: true
    exampleQuery: |
        query HourlyResults($appId: String!, $from: String, $to: String) {
          hourlyResults(appId: $appId, from: $from, to: $to) {
            appId
            date
            hour
            manufacturer
            dau
          }
        }
